name: mobile_template_for_lamm
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  common_template_for_lamm:
    path: ../common_template_for_lamm
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  library_architecture_mvvm_modify: ^6.1.1
  meta: ^1.15.0
  intl: ^0.19.0
  responsive_framework: ^1.5.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.25.14

flutter:
  assets:
    - assets/icon/app_icon.ico
    - assets/icon/app_icon.png
  uses-material-design: true
  generate: true